### ISSUE TITLE
?Where is the code

### ISSUE THREAD

**Issue by boomzero** [langningchen/Countdown#1]
~你这是学习 https://github.com/kelseyhightower/nocode 吗~

**Comment by boomzero** [comment]
宣传https://github.com/boomzero/Countdown

**Comment by langningchen** [comment]
写好了没传，因为我在学校写的，学校没有Git

**Comment by langningchen** [comment]
这是写了一个很简陋的C++ Windows图形化版本的，是不能用网页端的
